spring:
  application:
    name: Backend
  Jackson:
    serialization:
      fail-on-empty-beans: false
  main:
    lazy-initialization: true
  #datasoruce settings
  datasource:
    url: jdbc:postgresql://localhost:5432/CarryGo
    username: postgres
    password: postgres
    hikari:
      pool-name: VP-LOCAL-CONN-POOL
  #servlet Multipart Settings
  servlet:
    multipart:
      max-file-size: 5MB
      max-request-size: 5MB

  #jpa settings
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true

#mail Sender Settings
#  mail:
#    sender: valueplus-local
#    host: smtppro.zoho.com
#    port: 587
#    username: partner@valueplusagency.com
#    password: "ValueDEV1@"
#    properties:
#      mail:
#        transport:
#          protocol: smtp
#        smtp:
#          auth: true
#          ehlo:
#            name: smtp-relay.brevo.com
#          starttls:
#            enable: true
#        debug: true

server:
  port: 4545
  servlet:
    context-path: /api/v1

app:
  jwt-secret: 9a4f2c8d3b7a1e6f45c8a0b3f267d8b1d4e6f3c8a9d2b5f8e3a9c8b5f6v8a3d9
  jwt-expiration-ms: 86400000
  upload:
    diruploads: C:\Users\SHADOW\Pictures\Camera Roll
#if you need to save anything in cloud
aws:
  s3:
    bucketName: user_documents
    region: af-south-1
    folder: document-images
    accessKey: AKIATXI5FIOJPC46SQUT
    accessSecret: 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